// All OPSWAT doc products and PDF crawl targets.

const PRODUCTS = [
  { slug: 'cm',                     url: 'https://www.opswat.com/docs/cm' },
  { slug: 'mdcore',                 url: 'https://www.opswat.com/docs/mdcore' },
  { slug: 'mdicap',                 url: 'https://www.opswat.com/docs/mdicap' },
  { slug: 'mdkiosk',                url: 'https://www.opswat.com/docs/mdkiosk' },
  { slug: 'mdkiosk-linux',          url: 'https://www.opswat.com/docs/mdkiosk-linux' },
  { slug: 'mdendpoint',             url: 'https://www.opswat.com/docs/mdendpoint' },
  { slug: 'mdmft',                  url: 'https://www.opswat.com/docs/mdmft' },
  { slug: 'mdss',                   url: 'https://www.opswat.com/docs/mdss' },
  { slug: 'mdcloud',                url: 'https://www.opswat.com/docs/mdcloud' },
  { slug: 'filescan',               url: 'https://www.opswat.com/docs/filescan' },
  { slug: 'mddownloader',           url: 'https://www.opswat.com/docs/mddownloader' },
  { slug: 'mdcluster',              url: 'https://www.opswat.com/docs/mdcluster' },
  { slug: 'mdinsights',             url: 'https://www.opswat.com/docs/mdinsights' },
  { slug: 'mdndr',                  url: 'https://www.opswat.com/docs/mdndr' },
  { slug: 'supply-chain',           url: 'https://www.opswat.com/docs/supply-chain' },
  { slug: 'mdfs',                   url: 'https://www.opswat.com/docs/mdfs' },
  { slug: 'mdemail',                url: 'https://www.opswat.com/docs/mdemail' },
  { slug: 'mdces3',                 url: 'https://www.opswat.com/docs/mdces3' },
  { slug: 'manac',                  url: 'https://www.opswat.com/docs/manac' },
  { slug: 'macloud-sdp',            url: 'https://www.opswat.com/docs/macloud-sdp' },
  { slug: 'md-ot-security',         url: 'https://www.opswat.com/docs/md-ot-security' },
  { slug: 'metadefender-ot-access', url: 'https://www.opswat.com/docs/metadefender-ot-access' },
  { slug: 'my',                     url: 'https://www.opswat.com/docs/my' },
  { slug: 'myop',                   url: 'https://www.opswat.com/docs/myop' },
  { slug: 'ocm',                    url: 'https://www.opswat.com/docs/ocm' },
  { slug: 'mdsdk',                  url: 'https://www.opswat.com/docs/mdsdk' },
  { slug: 'netwalldiode',           url: 'https://www.opswat.com/docs/netwalldiode' },
  { slug: 'netwall',                url: 'https://www.opswat.com/docs/netwall' },
  { slug: 'mdtransferguard',        url: 'https://www.opswat.com/docs/mdtransferguard' },
  { slug: 'fenddiode',              url: 'https://www.opswat.com/docs/fenddiode' },
  { slug: 'mdmediafirewall',        url: 'https://www.opswat.com/docs/mdmediafirewall' },
  { slug: 'mdif4p',                 url: 'https://www.opswat.com/docs/mdif4p' },
  { slug: 'mddrive',                url: 'https://www.opswat.com/docs/mddrive' },
];

// Pages to crawl when hunting for PDF links
const CRAWL_TARGETS = [
  'https://www.opswat.com/resources',
  'https://www.opswat.com/resources/p2',
  'https://www.opswat.com/resources/p3',
  'https://www.opswat.com/resources/p4',
  'https://www.opswat.com/resources/p5',
  'https://www.opswat.com/resources/p6',
  'https://www.opswat.com/resources/p7',
  'https://www.opswat.com/resources/p8',
  'https://www.opswat.com/products/metadefender/core',
  'https://www.opswat.com/products/metadefender/icap',
  'https://www.opswat.com/products/metadefender/kiosk',
  'https://www.opswat.com/products/metadefender/endpoint',
  'https://www.opswat.com/products/metadefender/nac',
  'https://www.opswat.com/products/metadefender/aether',
  'https://www.opswat.com/products/metadefender/my-opswat-central-management',
  'https://www.opswat.com/products/metadefender/storage-security',
  'https://www.opswat.com/products/metadefender/drive',
  'https://www.opswat.com/solutions/file-security',
  'https://www.opswat.com/solutions/storage-security',
  'https://www.opswat.com/solutions/zero-trust-access',
  'https://www.opswat.com/solutions/ot-cps-protection',
  'https://www.opswat.com/solutions/peripheral-removable-media',
  'https://www.opswat.com/solutions/email-security',
  'https://www.opswat.com/solutions/managed-file-transfer',
];

// Only collect PDFs from this domain — skip external/partner PDFs
const PDF_HOST = 'static.opswat.com';

module.exports = { PRODUCTS, CRAWL_TARGETS, PDF_HOST };
